### ISSUE TITLE
Issues while running from macOS

### ISSUE THREAD

**Issue by uhlhosting** [cachewerk/k6#8]
Hi,

Just gave it a try, and I ended up with:

```
ERRO[0034] TypeError: Cannot read property 'length' of undefined
running at parseMetricsFromResponse (file:///Users/cosmic/Developer/WIP/ApisCP/k6-wp/lib/metrics.js:81:14(15))
default at addResponseMetrics (file:///Users/cosmic/Developer/WIP/ApisCP/k6-wp/lib/metrics.js:61:54(5))
	at file:///Users/cosmic/Developer/WIP/ApisCP/k6-wp/wp.js:41:31(51)
	at native  executor=constant-vus scenario=default source=stacktrace
```

**Comment by tillkruss** [comment]
Ah, that's because you don't have Object Cache Pro installed. I fixed it in faabfa6.
